### ISSUE TITLE
Building VTK_TRIANGLE 1 with less than three points, but VTK_TRIANGLE needs at least three points. Check the input

### ISSUE THREAD

**Issue by orena1** [mattions/neuronvisio#64]
This is what I get, and I can not see anything in Mayavi

```
@bream ~/Lab/GJ_Net_Model/Spikelets_reconstruct_network $ python
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from neuronvisio.controls import Controls
controls = Controls()   # starting the GUINEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits


>>> from neuron import h
>>> h("create soma")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'h' is not defined
>>> from neuron impoty h
  File "<stdin>", line 1
    from neuron impoty h
                     ^
SyntaxError: invalid syntax
>>> from neuron import h
>>> h("create soma")
1
>>> WARNING neuronvisio.manager 135   Warning: Some vectors could not be added.
Warning: In /feedstock_root/build_artefacts/recipe_root_1484429346876/work/VTK-7.1.0/Common/DataModel/vtkPolyData.cxx, line 1010
vtkPolyData (0x4be0200): Building VTK_TRIANGLE 0 with less than three points, but VTK_TRIANGLE needs at least three points. Check the input.

Warning: In /feedstock_root/build_artefacts/recipe_root_1484429346876/work/VTK-7.1.0/Common/DataModel/vtkPolyData.cxx, line 1023
vtkPolyData (0x4be0200): Building VTK_TRIANGLE 1 with less than three points, but VTK_TRIANGLE needs at least three points. Check the input.

Warning: In /feedstock_root/build_artefacts/recipe_root_1484429346876/work/VTK-7.1.0/Common/DataModel/vtkPolyData.cxx, line 1023
vtkPolyData (0x4be0200): Building VTK_TRIANGLE 2 with less than three points, but VTK_TRIANGLE needs at least three points. Check the input.

Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.tools.filters.SetActiveAttributeFactory object at 0x7fac0214f650>, trait: point_scalars, old value: , new value: v
Traceback (most recent call last):
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 198, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/core/trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
TraitError: The 'point_scalars_name' trait of a SetActiveAttribute instance must be one of [''], but a value of 'v' <type 'str'> was specified.
ERROR traits 238   Exception occurred in traits notification handler for object: <mayavi.tools.filters.SetActiveAttributeFactory object at 0x7fac0214f650>, trait: point_scalars, old value: , new value: v
Traceback (most recent call last):
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 198, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/core/trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
TraitError: The 'point_scalars_name' trait of a SetActiveAttribute instance must be one of [''], but a value of 'v' <type 'str'> was specified.
Traceback (most recent call last):
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/neuronvisio/controls.py", line 335, in launch_visio
    self.visio.draw_model()
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/neuronvisio/visio.py", line 295, in draw_model
    self.draw_mayavi(x, y, z, d, self.edges)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/neuronvisio/visio.py", line 367, in draw_mayavi
    self.draw_surface(v, 'v')
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/neuronvisio/visio.py", line 382, in draw_surface
    point_scalars=scalar_name)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 38, in the_function
    factory = factory_class(*args, **kwargs)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 163, in __init__
    self.set(**traits)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 180, in set
    self._anytrait_changed(trait, value)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/tools/pipe_base.py", line 198, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "/home/ls/users/oren.amsalem/anaconda2/lib/python2.7/site-packages/mayavi/core/trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
traits.trait_errors.TraitError: The 'point_scalars_name' trait of a SetActiveAttribute instance must be one of [''], but a value of 'v' <type 'str'> was specified```

Thanks.

**Comment by mattions** [comment]
I can reproduce this.
It may be related to this: https://github.com/enthought/mayavi/issues/380

Unfortunately in our case it seems we are already using the VTK 5.10, so I'm not sure what to do about. I'll try to investigate a little.

**Comment by mattions** [comment]
Actually on the enviroment is 

```
mayavi=4.5.0=py27_0
vtk=6.3.0=py27_1
```

So I'm not sure what is going on.

**Comment by orena1** [comment]
Any updates?
Thanks.
